# Generated by Django 5.0.6 on 2024-06-07 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='data_nascimento',
            new_name='data_nasc',
        ),
        migrations.RenameField(
            model_name='curso',
            old_name='codigo_curso',
            new_name='curso_id',
        ),
    ]
